name: BookMyShow Scraper

on:
  schedule:
    # Runs daily at 9:00 AM IST (3:30 AM UTC)
    - cron: '30 3 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
    - name: Run scraper
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      run: python scraper.py
      
    - name: Commit updated events file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add previous_events.json
        git diff --staged --quiet || git commit -m "Update events data - $(date)"
        git push
